// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAObQ_7bscEXjkjaj6PMF0pAxnvNLPwqqE',
    appId: '1:339280105724:web:40cfafbf2e575b25600779',
    messagingSenderId: '339280105724',
    projectId: 'studio-1613468706-6cd74',
    authDomain: 'studio-1613468706-6cd74.firebaseapp.com',
    storageBucket: 'studio-1613468706-6cd74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgiii9ei1yF1i-Seor_L7Dc7OlLO8cMA',
    appId: '1:339280105724:android:db20b6c60367a35c600779',
    messagingSenderId: '339280105724',
    projectId: 'studio-1613468706-6cd74',
    storageBucket: 'studio-1613468706-6cd74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofvqjPbBa-1zprzptCW4C9b6XuNL5wUA',
    appId: '1:339280105724:ios:9c00a03fc6ddafe1600779',
    messagingSenderId: '339280105724',
    projectId: 'studio-1613468706-6cd74',
    storageBucket: 'studio-1613468706-6cd74.firebasestorage.app',
    iosBundleId: 'com.example.saviaLightweight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAofvqjPbBa-1zprzptCW4C9b6XuNL5wUA',
    appId: '1:339280105724:ios:9c00a03fc6ddafe1600779',
    messagingSenderId: '339280105724',
    projectId: 'studio-1613468706-6cd74',
    storageBucket: 'studio-1613468706-6cd74.firebasestorage.app',
    iosBundleId: 'com.example.saviaLightweight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQCebP5QNUX8oOrPhSr5hHRQLNQ6dh4gA',
    appId: '1:339280105724:web:7a5c176217da7dee600779',
    messagingSenderId: '339280105724',
    projectId: 'studio-1613468706-6cd74',
    authDomain: 'studio-1613468706-6cd74.firebaseapp.com',
    storageBucket: 'studio-1613468706-6cd74.firebasestorage.app',
  );
}
